# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
FROM node:18-alpine AS builder

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY src ./src
COPY tsconfig.json ./

# Build the project
RUN npm run build

# Stage 2: Release
FROM node:18-alpine

WORKDIR /app

# Copy the build output and package files
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json /app/package-lock.json ./

# Set environment to production
ENV NODE_ENV=production

# Install only production dependencies
RUN npm install --omit=dev

# Define the command to run the application
ENTRYPOINT ["node", "build/index.js"]